param($data)
# delete PlayWithMPV://
$data=$data.subString(14)
# delete /
$data=$data.subString(0, $data.Length-1)+$data.subString($data.Length-1).replace("/", "");

# base64 decode
$data=[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($data))

# param split
$datas=$data.split("\|")
$domain=$datas[0]
$videoUrl=$datas[1]
$title=$datas[2]
echo "================================ 域名 domain ======================================="$domain
echo ""
echo ""
echo ""
echo "============================ 视频链接 video url ===================================="$videoUrl
echo ""
echo ""
echo ""
echo "================================ 标题 title ========================================"$title
echo ""
echo ""
echo ""
echo "========================== 开始播放 start playing ==================================="
echo ""

# deal bilibili video url
$bilibili="www.bilibili.com"
$youtube="www.youtube.com"
if($domain -like $bilibili){
    echo "#EXTM3U" > $PSScriptRoot\_tmp_bilibili.m3u
	echo "#Generated by PlayWithMPV_LuckyPuppy514" >> $PSScriptRoot\_tmp_bilibili.m3u
	echo "#EXTINF:$title" >> $PSScriptRoot\_tmp_bilibili.m3u
	echo $videoUrl >> $PSScriptRoot\_tmp_bilibili.m3u
	mpv -title $title --http-header-fields="referer:https://www.bilibili.com/","user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0" --playlist=$PSScriptRoot\_tmp_bilibili.m3u
    exit
}

# deal youtube video url
if($domain -like $youtube){
    mpv $videoUrl
    exit
}

# deal other video url
mpv $videoUrl -title $title
exit
